#pragma config(Sensor, in5,    armPot,         sensorPotentiometer)
#pragma config(Sensor, dgtl1,  encoder1,       sensorQuadEncoder)
#pragma config(Sensor, dgtl6,  LED1,           sensorLEDtoVCC)
#pragma config(Sensor, dgtl11, sonar1,         sensorSONAR_mm)
#pragma config(Motor,  port3,           backLeft,      tmotorVex393, openLoop)
#pragma config(Motor,  port4,           backRight,     tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port5,           frontRight,    tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port6,           frontLeft,     tmotorVex393, openLoop)
#pragma config(Motor,  port7,           armLeft,       tmotorVex269, openLoop)
#pragma config(Motor,  port8,           armRight,      tmotorVex269, openLoop, reversed)
#pragma config(Motor,  port9,           eleBotLeft,    tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port10,          eleBotRight,   tmotorVex393, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

bool close = false;

void getCloser()
{
	if(SensorValue[sonar1] > 99 || SensorValue[sonar1] == -1)
	{
		motor[backLeft] = -45;
		motor[frontLeft] = -45;
		motor[backRight] = -45;
		motor[frontRight] = -45;
		close = false;
	}
	if(SensorValue[sonar1] < 99)
	{
		motor[backLeft] = 0;
		motor[frontLeft] = 0;
		motor[backRight] = 0;
		motor[frontRight] = 0;
		close = true;
	}
}

void turn90(int positive)  //1 = right, -1 = left
{
	motor[frontLeft] = 127 * positive;
	motor[frontRight] = -127 * positive;
	motor[backLeft] = 127 * positive;
	motor[backRight] = -127 * positive;
	wait1Msec(600);
	motor[backLeft] = 0;
	motor[frontLeft] = 0;
	motor[backRight] = 0;
	motor[frontRight] = 0;
}

task main()
{
	ClearTimer(T1);
	SensorValue[LED1] = 0;
	bool done = false;
	while(true)
	{
		//Arcade drive
		motor[backLeft] = vexRT[Ch3] + vexRT[Ch4];
		motor[frontLeft] = vexRT[Ch3] + vexRT[Ch4];
		motor[backRight] = vexRT[Ch3] - vexRT[Ch4];
		motor[frontRight] = vexRT[Ch3] - vexRT[Ch4];

		//Pickup arm
		if(SensorValue[armPot] < 3501)
		{
			motor[armLeft] = vexRT[Ch2];
			motor[armRight] = vexRT[Ch2];
		}
		else
		{
			motor[armLeft] = -35;
			motor[armRight] = -35;
		}

		//Elevator
		if(vexRT[Btn5U] == true)
		{
			motor[eleBotLeft] = 127;
			motor[eleBotRight] = 127;
		}
		else
		{
			if(vexRT[Btn5D] == true)
			{
				motor[eleBotLeft] = -100;
				motor[eleBotRight] = -100;
			}
			else
			{
				motor[eleBotLeft] = 0;
				motor[eleBotRight] = 0;
			}
		}
		//Getting 'closer'
		if(vexRT[Btn8R] == true)
		{
			getCloser();
		}

		//Move a little bit
		if(vexRT[Btn7U]== true)
		{
			motor[backLeft] = 35;
			motor[frontLeft] = 35;
			motor[backRight] = 35;
			motor[frontRight] = 35;
		}
		else
		{
			if(vexRT[Btn7D] == true)
			{
				motor[backLeft] = -35;
				motor[frontLeft] = -35;
				motor[backRight] = -35;
				motor[frontRight] = -35;
			}
			else
			{
				if(vexRT[Btn7L] == true)
				{
					motor[backLeft] = -35;
					motor[frontLeft] = -35;
					motor[backRight] = 35;
					motor[frontRight] = 35;
				}
				else
				{
					if(vexRT[Btn7R] == true)
					{
						motor[backLeft] = 35;
						motor[frontLeft] = 35;
						motor[backRight] = -35;
						motor[frontRight] = -35;
					}
				}
			}
		}
		//test auto
		if(vexRT[Btn8U] == true && vexRT[Btn6U] == true && vexRT[Btn6D] == true)
		{
			//while(done == false)
			//{
				close = false;
				//put arm down
				//motor[armRight] = 75;
				//motor[armLeft] = 75;
				//wait1Msec(800);
				//motor[armRight] = 0;
				//motor[armLeft] = 0;

				//Align with sacks
				//turn90(1);
				//motor[frontRight] = 35;
				//motor[backRight] = 35;
				//motor[frontLeft] = 35;
				//motor[backLeft] = 35;
				//wait1Msec(500);
				//motor[frontRight] = 0;
				//motor[backRight] = 0;
				//motor[frontLeft] = 0;
				//motor[backLeft] = 0;
				//turn90(-1);

				//drive forward
				//motor[frontRight] = 127;
				//motor[backRight] = 127;
				//motor[frontLeft] = 127;
				//motor[backLeft] = 127;
				//wait1Msec(1250);
				//motor[frontRight] = 0;
				//motor[backRight] = 0;
				//motor[frontLeft] = 0;
				//motor[backLeft] = 0;

				//pickup sacks
				//motor[armRight] = -127;
				//motor[armLeft] = -127;
				//wait1Msec(1350);
				//motor[armRight] = 0;
				//motor[armLeft] = 0;
				//wait1Msec(1000);
				//motor[armLeft] = 75;
				//motor[armRight] = 75;
				//wait1Msec(250);
				//motor[armLeft] = 0;
				//motor[armRight] = 0;

				//get to trough
				//motor[frontRight] = -60;
				//motor[backRight] = -60;
				//motor[frontLeft] = -60;
				//motor[backLeft] = -60;
				//wait1Msec(1000);
				//motor[frontRight] = 0;
				//motor[backRight] = 0;
				//motor[frontLeft] = 0;
				//motor[backLeft] = 0;
				//turn90(-1);
				//motor[frontRight] = 60;
				//motor[backRight] = 60;
				//motor[frontLeft] = 60;
				//motor[backLeft] = 60;
				//wait1Msec(1000);
				//motor[frontRight] = 0;
				//motor[backRight] = 0;
				//motor[frontLeft] = 0;
				//motor[backLeft] = 0;
				//turn90(-1);
				motor[frontRight] = -65;
				motor[backRight] = -65;
				motor[frontLeft] = -65;
				motor[backLeft] = -65;
				wait1Msec(2500);
				motor[frontRight] = 0;
				motor[backRight] = 0;
				motor[frontLeft] = 0;
				motor[backLeft] = 0;

				//score
				//while(close == false)
				//{
				//	getCloser();
				//}
				motor[eleBotLeft] = 127;
				motor[eleBotRight] = 127;
				wait1Msec(2806);
				motor[eleBotRight] = 0;
				motor[eleBotLeft] = 0;
				wait1Msec(500);
				motor[eleBotLeft] = -127;
				motor[eleBotRight] = -127;
				wait1Msec(1000);
				motor[eleBotRight] = 0;
				motor[eleBotLeft] = 0;
			done = true;
			//}
		}
		else done = false;
	}//while loop
}
